//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 04:20:54 PM EET 
//

package com.xmlparsing;

import javax.xml.bind.annotation.*;


/**
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "language",
    "contexts",
    "rules"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(required = true)
    private String language;
    @XmlElement(required = true)
    private Contexts contexts;
    @XmlElement(required = true)
    private Rules rules;

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Gets the value of the contexts property.
     *
     * @return
     *     possible object is
     *     {@link Contexts }
     *
     */
    public Contexts getContexts() {
        return contexts;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link Rules }
     *     
     */
    public Rules getRules() {
        return rules;
    }

}
